// Placeholder images using DiceBear Shapes API (deterministic, no auth needed)
function venueImage(seed) {
  return `https://api.dicebear.com/9.x/shapes/svg?seed=${encodeURIComponent(seed)}&backgroundColor=111827&shape1Color=3b82f6,6366f1,8b5cf6,ec4899,f59e0b,10b981&shape2Color=3b82f6,6366f1,8b5cf6,ec4899,f59e0b,10b981&shape3Color=3b82f6,6366f1,8b5cf6,ec4899,f59e0b,10b981`
}

export const sampleVenues = [
  {
    id: 1,
    name: "The Goal Line Sports Bar",
    category: "Sports Bar",
    address: "245 W 28th St",
    city: "New York",
    state: "NY",
    lat: 40.7468,
    lng: -73.9935,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=245+W+28th+St+New+York",
    logo_url: venueImage("goal-line"),
    opening_times: {
      monday: { open: "11:00", close: "01:00" },
      tuesday: { open: "11:00", close: "01:00" },
      wednesday: { open: "11:00", close: "01:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "10:00", close: "02:00" },
      sunday: { open: "10:00", close: "00:00" },
    },
  },
  {
    id: 2,
    name: "Futbol Cantina",
    category: "Mexican",
    address: "1820 N Milwaukee Ave",
    city: "Chicago",
    state: "IL",
    lat: 41.9135,
    lng: -87.6684,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1820+N+Milwaukee+Ave+Chicago",
    logo_url: venueImage("futbol-cantina"),
    opening_times: {
      monday: { open: "12:00", close: "23:00" },
      tuesday: { open: "12:00", close: "23:00" },
      wednesday: { open: "12:00", close: "23:00" },
      thursday: { open: "12:00", close: "00:00" },
      friday: { open: "12:00", close: "01:00" },
      saturday: { open: "11:00", close: "01:00" },
      sunday: { open: "11:00", close: "22:00" },
    },
  },
  {
    id: 3,
    name: "Pitch & Pint Brewery",
    category: "Brewery",
    address: "520 Haight St",
    city: "San Francisco",
    state: "CA",
    lat: 37.7719,
    lng: -122.4312,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=520+Haight+St+San+Francisco",
    logo_url: venueImage("pitch-pint"),
    opening_times: {
      monday: { open: "14:00", close: "23:00" },
      tuesday: { open: "14:00", close: "23:00" },
      wednesday: { open: "14:00", close: "23:00" },
      thursday: { open: "14:00", close: "00:00" },
      friday: { open: "12:00", close: "01:00" },
      saturday: { open: "11:00", close: "01:00" },
      sunday: { open: "11:00", close: "22:00" },
    },
  },
  {
    id: 4,
    name: "The Rooftop at World Cup",
    category: "Rooftop",
    address: "101 Ocean Dr",
    city: "Miami",
    state: "FL",
    lat: 25.7785,
    lng: -80.1300,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=101+Ocean+Dr+Miami",
    logo_url: venueImage("rooftop-wc"),
    opening_times: {
      monday: { open: "16:00", close: "00:00" },
      tuesday: { open: "16:00", close: "00:00" },
      wednesday: { open: "16:00", close: "00:00" },
      thursday: { open: "16:00", close: "01:00" },
      friday: { open: "15:00", close: "02:00" },
      saturday: { open: "12:00", close: "02:00" },
      sunday: { open: "12:00", close: "23:00" },
    },
  },
  {
    id: 5,
    name: "Red Card Pub",
    category: "Pub",
    address: "4521 Maple Ave",
    city: "Dallas",
    state: "TX",
    lat: 32.8143,
    lng: -96.7984,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=4521+Maple+Ave+Dallas",
    logo_url: venueImage("red-card"),
    opening_times: {
      monday: { open: "11:00", close: "00:00" },
      tuesday: { open: "11:00", close: "00:00" },
      wednesday: { open: "11:00", close: "00:00" },
      thursday: { open: "11:00", close: "01:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "10:00", close: "02:00" },
      sunday: { open: "10:00", close: "23:00" },
    },
  },
  {
    id: 6,
    name: "Offside American Grill",
    category: "American Grill",
    address: "789 Broadway",
    city: "New York",
    state: "NY",
    lat: 40.7290,
    lng: -73.9932,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=789+Broadway+New+York",
    logo_url: venueImage("offside-grill"),
    opening_times: {
      monday: { open: "11:00", close: "23:00" },
      tuesday: { open: "11:00", close: "23:00" },
      wednesday: { open: "11:00", close: "23:00" },
      thursday: { open: "11:00", close: "00:00" },
      friday: { open: "11:00", close: "01:00" },
      saturday: { open: "10:00", close: "01:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
  },
  {
    id: 7,
    name: "Hat Trick Cocktails",
    category: "Cocktail Bar",
    address: "2100 Main St",
    city: "Los Angeles",
    state: "CA",
    lat: 34.0407,
    lng: -118.2468,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=2100+Main+St+Los+Angeles",
    logo_url: venueImage("hat-trick"),
    opening_times: {
      monday: { open: "17:00", close: "01:00" },
      tuesday: { open: "17:00", close: "01:00" },
      wednesday: { open: "17:00", close: "01:00" },
      thursday: { open: "17:00", close: "02:00" },
      friday: { open: "16:00", close: "02:00" },
      saturday: { open: "15:00", close: "02:00" },
      sunday: { open: "15:00", close: "00:00" },
    },
  },
  {
    id: 8,
    name: "Kickoff Family Restaurant",
    category: "Family Restaurant",
    address: "350 Queen St W",
    city: "Toronto",
    state: "ON",
    lat: 43.6496,
    lng: -79.3948,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=350+Queen+St+W+Toronto",
    logo_url: venueImage("kickoff-family"),
    opening_times: {
      monday: { open: "09:00", close: "22:00" },
      tuesday: { open: "09:00", close: "22:00" },
      wednesday: { open: "09:00", close: "22:00" },
      thursday: { open: "09:00", close: "23:00" },
      friday: { open: "09:00", close: "00:00" },
      saturday: { open: "08:00", close: "00:00" },
      sunday: { open: "08:00", close: "21:00" },
    },
  },
  {
    id: 9,
    name: "Corner Kick Cafe",
    category: "Cafe",
    address: "99 Kensington Ave",
    city: "Toronto",
    state: "ON",
    lat: 43.6545,
    lng: -79.4015,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=99+Kensington+Ave+Toronto",
    logo_url: venueImage("corner-kick"),
    opening_times: {
      monday: { open: "07:00", close: "18:00" },
      tuesday: { open: "07:00", close: "18:00" },
      wednesday: { open: "07:00", close: "18:00" },
      thursday: { open: "07:00", close: "20:00" },
      friday: { open: "07:00", close: "20:00" },
      saturday: { open: "08:00", close: "20:00" },
      sunday: { open: "08:00", close: "17:00" },
    },
  },
  {
    id: 10,
    name: "Penalty Box Wings & Beer",
    category: "Sports Bar",
    address: "1555 Blake St",
    city: "Denver",
    state: "CO",
    lat: 39.7554,
    lng: -104.9946,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1555+Blake+St+Denver",
    logo_url: venueImage("penalty-box"),
    opening_times: {
      monday: { open: "11:00", close: "00:00" },
      tuesday: { open: "11:00", close: "00:00" },
      wednesday: { open: "11:00", close: "00:00" },
      thursday: { open: "11:00", close: "01:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "09:00", close: "02:00" },
      sunday: { open: "09:00", close: "23:00" },
    },
  },
  {
    id: 11,
    name: "Crossbar Brewing Co.",
    category: "Brewery",
    address: "312 N 3rd St",
    city: "Minneapolis",
    state: "MN",
    lat: 44.9824,
    lng: -93.2727,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=312+N+3rd+St+Minneapolis",
    logo_url: venueImage("crossbar-brewing"),
    opening_times: {
      monday: { closed: true },
      tuesday: { open: "15:00", close: "23:00" },
      wednesday: { open: "15:00", close: "23:00" },
      thursday: { open: "15:00", close: "00:00" },
      friday: { open: "14:00", close: "01:00" },
      saturday: { open: "12:00", close: "01:00" },
      sunday: { open: "12:00", close: "22:00" },
    },
  },
  {
    id: 12,
    name: "Golden Boot Gastropub",
    category: "Pub",
    address: "847 Decatur St",
    city: "New Orleans",
    state: "LA",
    lat: 29.9574,
    lng: -90.0644,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=847+Decatur+St+New+Orleans",
    logo_url: venueImage("golden-boot"),
    opening_times: {
      monday: { open: "11:00", close: "01:00" },
      tuesday: { open: "11:00", close: "01:00" },
      wednesday: { open: "11:00", close: "01:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "10:00", close: "02:00" },
      saturday: { open: "10:00", close: "02:00" },
      sunday: { open: "10:00", close: "00:00" },
    },
  },
  {
    id: 13,
    name: "The Volley Rooftop Lounge",
    category: "Rooftop",
    address: "2250 Peachtree Rd NW",
    city: "Atlanta",
    state: "GA",
    lat: 33.8038,
    lng: -84.3878,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=2250+Peachtree+Rd+NW+Atlanta",
    logo_url: venueImage("volley-rooftop"),
    opening_times: {
      monday: { closed: true },
      tuesday: { closed: true },
      wednesday: { open: "17:00", close: "00:00" },
      thursday: { open: "17:00", close: "00:00" },
      friday: { open: "16:00", close: "02:00" },
      saturday: { open: "13:00", close: "02:00" },
      sunday: { open: "13:00", close: "23:00" },
    },
  },
  {
    id: 14,
    name: "Stoppage Time Sports Bar",
    category: "Sports Bar",
    address: "714 Pike St",
    city: "Seattle",
    state: "WA",
    lat: 47.6116,
    lng: -122.3344,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=714+Pike+St+Seattle",
    logo_url: venueImage("stoppage-time"),
    opening_times: {
      monday: { open: "11:00", close: "00:00" },
      tuesday: { open: "11:00", close: "00:00" },
      wednesday: { open: "11:00", close: "00:00" },
      thursday: { open: "11:00", close: "01:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "09:00", close: "02:00" },
      sunday: { open: "09:00", close: "23:00" },
    },
  },
  {
    id: 15,
    name: "El Delantero Mexican Kitchen",
    category: "Mexican",
    address: "4890 W Sunset Blvd",
    city: "Los Angeles",
    state: "CA",
    lat: 34.0967,
    lng: -118.3277,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=4890+W+Sunset+Blvd+Los+Angeles",
    logo_url: venueImage("el-delantero"),
    opening_times: {
      monday: { open: "11:00", close: "22:00" },
      tuesday: { open: "11:00", close: "22:00" },
      wednesday: { open: "11:00", close: "22:00" },
      thursday: { open: "11:00", close: "23:00" },
      friday: { open: "11:00", close: "00:00" },
      saturday: { open: "10:00", close: "00:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
  },
  {
    id: 16,
    name: "Shamrock & Shin Pads",
    category: "Irish Bar",
    address: "163 Stuart St",
    city: "Boston",
    state: "MA",
    lat: 42.3510,
    lng: -71.0614,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=163+Stuart+St+Boston",
    logo_url: venueImage("shamrock-shin"),
    opening_times: {
      monday: { open: "12:00", close: "01:00" },
      tuesday: { open: "12:00", close: "01:00" },
      wednesday: { open: "12:00", close: "01:00" },
      thursday: { open: "12:00", close: "02:00" },
      friday: { open: "12:00", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "01:00" },
    },
  },
  {
    id: 17,
    name: "Nutmeg Noodle & Wing Joint",
    category: "Wing Joint",
    address: "2040 Broadway",
    city: "Nashville",
    state: "TN",
    lat: 36.1567,
    lng: -86.7825,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=2040+Broadway+Nashville",
    logo_url: venueImage("nutmeg-wings"),
    opening_times: {
      monday: { open: "11:00", close: "23:00" },
      tuesday: { open: "11:00", close: "23:00" },
      wednesday: { open: "11:00", close: "23:00" },
      thursday: { open: "11:00", close: "00:00" },
      friday: { open: "11:00", close: "01:00" },
      saturday: { open: "11:00", close: "01:00" },
      sunday: { open: "12:00", close: "22:00" },
    },
  },
  {
    id: 18,
    name: "Flick On Cafe",
    category: "Cafe",
    address: "512 NW 23rd Ave",
    city: "Portland",
    state: "OR",
    lat: 45.5269,
    lng: -122.6992,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=512+NW+23rd+Ave+Portland",
    logo_url: venueImage("flick-on-cafe"),
    opening_times: {
      monday: { open: "06:30", close: "16:00" },
      tuesday: { open: "06:30", close: "16:00" },
      wednesday: { open: "06:30", close: "16:00" },
      thursday: { open: "06:30", close: "17:00" },
      friday: { open: "06:30", close: "17:00" },
      saturday: { open: "07:00", close: "17:00" },
      sunday: { open: "07:00", close: "15:00" },
    },
  },
  {
    id: 19,
    name: "Tiki Tackle Cocktail Bar",
    category: "Cocktail Bar",
    address: "3340 Las Vegas Blvd S",
    city: "Las Vegas",
    state: "NV",
    lat: 36.1147,
    lng: -115.1733,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=3340+Las+Vegas+Blvd+S+Las+Vegas",
    logo_url: venueImage("tiki-tackle"),
    opening_times: {
      monday: { open: "16:00", close: "02:00" },
      tuesday: { open: "16:00", close: "02:00" },
      wednesday: { open: "16:00", close: "02:00" },
      thursday: { open: "15:00", close: "02:00" },
      friday: { open: "14:00", close: "04:00" },
      saturday: { open: "14:00", close: "04:00" },
      sunday: { open: "15:00", close: "02:00" },
    },
  },
  {
    id: 20,
    name: "The Striker's Slice",
    category: "Pizza Place",
    address: "6012 N Broadway",
    city: "Chicago",
    state: "IL",
    lat: 41.9810,
    lng: -87.6601,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=6012+N+Broadway+Chicago",
    logo_url: venueImage("strikers-slice"),
    opening_times: {
      monday: { open: "11:00", close: "22:00" },
      tuesday: { open: "11:00", close: "22:00" },
      wednesday: { open: "11:00", close: "22:00" },
      thursday: { open: "11:00", close: "23:00" },
      friday: { open: "11:00", close: "00:00" },
      saturday: { open: "10:00", close: "00:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
  },
  {
    id: 21,
    name: "Header & Hops",
    category: "Brewery",
    address: "1621 Locust St",
    city: "Philadelphia",
    state: "PA",
    lat: 39.9481,
    lng: -75.1656,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1621+Locust+St+Philadelphia",
    logo_url: venueImage("header-hops"),
    opening_times: {
      monday: { open: "14:00", close: "23:00" },
      tuesday: { open: "14:00", close: "23:00" },
      wednesday: { open: "14:00", close: "23:00" },
      thursday: { open: "14:00", close: "00:00" },
      friday: { open: "12:00", close: "01:00" },
      saturday: { open: "11:00", close: "01:00" },
      sunday: { open: "11:00", close: "22:00" },
    },
  },
  {
    id: 22,
    name: "Own Goal American Grill",
    category: "American Grill",
    address: "980 Commerce St",
    city: "Dallas",
    state: "TX",
    lat: 32.7800,
    lng: -96.8048,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=980+Commerce+St+Dallas",
    logo_url: venueImage("own-goal-grill"),
    opening_times: {
      monday: { open: "11:00", close: "22:00" },
      tuesday: { open: "11:00", close: "22:00" },
      wednesday: { open: "11:00", close: "22:00" },
      thursday: { open: "11:00", close: "23:00" },
      friday: { open: "11:00", close: "00:00" },
      saturday: { open: "10:00", close: "00:00" },
      sunday: { open: "10:00", close: "21:00" },
    },
  },
  {
    id: 23,
    name: "The Ultras Irish Pub",
    category: "Irish Bar",
    address: "2315 Elliston Pl",
    city: "Nashville",
    state: "TN",
    lat: 36.1499,
    lng: -86.8043,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=2315+Elliston+Pl+Nashville",
    logo_url: venueImage("ultras-irish"),
    opening_times: {
      monday: { open: "15:00", close: "01:00" },
      tuesday: { open: "15:00", close: "01:00" },
      wednesday: { open: "15:00", close: "01:00" },
      thursday: { open: "15:00", close: "01:00" },
      friday: { open: "14:00", close: "02:00" },
      saturday: { open: "12:00", close: "02:00" },
      sunday: { open: "12:00", close: "00:00" },
    },
  },
  {
    id: 24,
    name: "Bicycle Kick Family Diner",
    category: "Family Restaurant",
    address: "450 W Temple St",
    city: "Salt Lake City",
    state: "UT",
    lat: 40.7608,
    lng: -111.8966,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=450+W+Temple+St+Salt+Lake+City",
    logo_url: venueImage("bicycle-kick-diner"),
    opening_times: {
      monday: { open: "08:00", close: "21:00" },
      tuesday: { open: "08:00", close: "21:00" },
      wednesday: { open: "08:00", close: "21:00" },
      thursday: { open: "08:00", close: "21:00" },
      friday: { open: "08:00", close: "22:00" },
      saturday: { open: "07:30", close: "22:00" },
      sunday: { open: "07:30", close: "20:00" },
    },
  },
  {
    id: 25,
    name: "Free Kick Sports Bar",
    category: "Sports Bar",
    address: "1802 Guadalupe St",
    city: "Austin",
    state: "TX",
    lat: 30.2887,
    lng: -97.7436,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1802+Guadalupe+St+Austin",
    logo_url: venueImage("free-kick-austin"),
    opening_times: {
      monday: { open: "14:00", close: "01:00" },
      tuesday: { open: "14:00", close: "01:00" },
      wednesday: { open: "14:00", close: "01:00" },
      thursday: { open: "14:00", close: "02:00" },
      friday: { open: "12:00", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "00:00" },
    },
  },
  {
    id: 26,
    name: "Panenka Pizzeria",
    category: "Pizza Place",
    address: "5501 Penn Ave",
    city: "Pittsburgh",
    state: "PA",
    lat: 40.4650,
    lng: -79.9418,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=5501+Penn+Ave+Pittsburgh",
    logo_url: venueImage("panenka-pizza"),
    opening_times: {
      monday: { closed: true },
      tuesday: { open: "11:30", close: "22:00" },
      wednesday: { open: "11:30", close: "22:00" },
      thursday: { open: "11:30", close: "22:00" },
      friday: { open: "11:30", close: "23:00" },
      saturday: { open: "11:00", close: "23:00" },
      sunday: { open: "11:00", close: "21:00" },
    },
  },
  {
    id: 27,
    name: "La Cancha Mexican Cantina",
    category: "Mexican",
    address: "2210 S Michigan Ave",
    city: "Chicago",
    state: "IL",
    lat: 41.8498,
    lng: -87.6231,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=2210+S+Michigan+Ave+Chicago",
    logo_url: venueImage("la-cancha"),
    opening_times: {
      monday: { open: "11:00", close: "22:00" },
      tuesday: { open: "11:00", close: "22:00" },
      wednesday: { open: "11:00", close: "23:00" },
      thursday: { open: "11:00", close: "23:00" },
      friday: { open: "11:00", close: "00:00" },
      saturday: { open: "10:00", close: "00:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
  },
  {
    id: 28,
    name: "Offside Wing House",
    category: "Wing Joint",
    address: "3300 Peachtree Rd NE",
    city: "Atlanta",
    state: "GA",
    lat: 33.8488,
    lng: -84.3638,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=3300+Peachtree+Rd+NE+Atlanta",
    logo_url: venueImage("offside-wings"),
    opening_times: {
      monday: { open: "11:00", close: "23:00" },
      tuesday: { open: "11:00", close: "23:00" },
      wednesday: { open: "11:00", close: "23:00" },
      thursday: { open: "11:00", close: "00:00" },
      friday: { open: "11:00", close: "01:00" },
      saturday: { open: "11:00", close: "01:00" },
      sunday: { open: "12:00", close: "22:00" },
    },
  },
  {
    id: 29,
    name: "The Chip Shot Pub",
    category: "Pub",
    address: "2850 Woodward Ave",
    city: "Detroit",
    state: "MI",
    lat: 42.3589,
    lng: -83.0614,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=2850+Woodward+Ave+Detroit",
    logo_url: venueImage("chip-shot-pub"),
    opening_times: {
      monday: { open: "15:00", close: "00:00" },
      tuesday: { open: "15:00", close: "00:00" },
      wednesday: { open: "15:00", close: "00:00" },
      thursday: { open: "15:00", close: "01:00" },
      friday: { open: "14:00", close: "02:00" },
      saturday: { open: "12:00", close: "02:00" },
      sunday: { open: "12:00", close: "23:00" },
    },
  },
  {
    id: 30,
    name: "Keeper's Rooftop Bar",
    category: "Rooftop",
    address: "400 Horton Plaza",
    city: "San Diego",
    state: "CA",
    lat: 32.7150,
    lng: -117.1625,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=400+Horton+Plaza+San+Diego",
    logo_url: venueImage("keepers-rooftop"),
    opening_times: {
      monday: { closed: true },
      tuesday: { open: "17:00", close: "01:00" },
      wednesday: { open: "17:00", close: "01:00" },
      thursday: { open: "16:00", close: "01:00" },
      friday: { open: "15:00", close: "02:00" },
      saturday: { open: "13:00", close: "02:00" },
      sunday: { open: "13:00", close: "00:00" },
    },
  },
  {
    id: 31,
    name: "First Touch Cafe",
    category: "Cafe",
    address: "620 Robson St",
    city: "Vancouver",
    state: "BC",
    lat: 49.2809,
    lng: -123.1219,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=620+Robson+St+Vancouver",
    logo_url: venueImage("first-touch-cafe"),
    opening_times: {
      monday: { open: "07:00", close: "17:00" },
      tuesday: { open: "07:00", close: "17:00" },
      wednesday: { open: "07:00", close: "17:00" },
      thursday: { open: "07:00", close: "18:00" },
      friday: { open: "07:00", close: "18:00" },
      saturday: { open: "07:30", close: "18:00" },
      sunday: { open: "08:00", close: "16:00" },
    },
  },
  {
    id: 32,
    name: "Dribble & Grill",
    category: "American Grill",
    address: "888 N Orange Ave",
    city: "Orlando",
    state: "FL",
    lat: 28.5494,
    lng: -81.3789,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=888+N+Orange+Ave+Orlando",
    logo_url: venueImage("dribble-grill"),
    opening_times: {
      monday: { open: "11:00", close: "22:00" },
      tuesday: { open: "11:00", close: "22:00" },
      wednesday: { open: "11:00", close: "22:00" },
      thursday: { open: "11:00", close: "23:00" },
      friday: { open: "11:00", close: "00:00" },
      saturday: { open: "10:00", close: "00:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
  },
  {
    id: 33,
    name: "The Touchline Pub",
    category: "Pub",
    address: "1550 Rue Crescent",
    city: "Montreal",
    state: "QC",
    lat: 45.4972,
    lng: -73.5802,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1550+Rue+Crescent+Montreal",
    logo_url: venueImage("touchline-pub"),
    opening_times: {
      monday: { open: "12:00", close: "01:00" },
      tuesday: { open: "12:00", close: "01:00" },
      wednesday: { open: "12:00", close: "01:00" },
      thursday: { open: "12:00", close: "02:00" },
      friday: { open: "12:00", close: "03:00" },
      saturday: { open: "11:00", close: "03:00" },
      sunday: { open: "11:00", close: "01:00" },
    },
  },
  {
    id: 34,
    name: "Clearance Header Sports Bar",
    category: "Sports Bar",
    address: "2701 N Husbands St",
    city: "Tampa",
    state: "FL",
    lat: 27.9696,
    lng: -82.4572,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=2701+N+Husbands+St+Tampa",
    logo_url: venueImage("clearance-header"),
    opening_times: {
      monday: { open: "12:00", close: "00:00" },
      tuesday: { open: "12:00", close: "00:00" },
      wednesday: { open: "12:00", close: "00:00" },
      thursday: { open: "12:00", close: "01:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "00:00" },
    },
  },
  {
    id: 35,
    name: "The Keeper's Keg",
    category: "Brewery",
    address: "2124 E Johnson St",
    city: "Milwaukee",
    state: "WI",
    lat: 43.0582,
    lng: -87.8876,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=2124+E+Johnson+St+Milwaukee",
    logo_url: venueImage("keepers-keg"),
    opening_times: {
      monday: { closed: true },
      tuesday: { open: "15:00", close: "23:00" },
      wednesday: { open: "15:00", close: "23:00" },
      thursday: { open: "15:00", close: "00:00" },
      friday: { open: "14:00", close: "01:00" },
      saturday: { open: "12:00", close: "01:00" },
      sunday: { open: "12:00", close: "21:00" },
    },
  },
  {
    id: 36,
    name: "El Portero Mexican Bar & Grill",
    category: "Mexican",
    address: "4120 San Felipe St",
    city: "Houston",
    state: "TX",
    lat: 29.7471,
    lng: -95.4432,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=4120+San+Felipe+St+Houston",
    logo_url: venueImage("el-portero"),
    opening_times: {
      monday: { open: "11:00", close: "22:00" },
      tuesday: { open: "11:00", close: "22:00" },
      wednesday: { open: "11:00", close: "22:00" },
      thursday: { open: "11:00", close: "23:00" },
      friday: { open: "11:00", close: "00:00" },
      saturday: { open: "10:00", close: "00:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
  },
  {
    id: 37,
    name: "Volante Cocktail Lounge",
    category: "Cocktail Bar",
    address: "305 5th Ave S",
    city: "Nashville",
    state: "TN",
    lat: 36.1551,
    lng: -86.7761,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=305+5th+Ave+S+Nashville",
    logo_url: venueImage("volante-lounge"),
    opening_times: {
      monday: { closed: true },
      tuesday: { open: "18:00", close: "01:00" },
      wednesday: { open: "18:00", close: "01:00" },
      thursday: { open: "17:00", close: "02:00" },
      friday: { open: "16:00", close: "02:00" },
      saturday: { open: "15:00", close: "02:00" },
      sunday: { open: "16:00", close: "00:00" },
    },
  },
  {
    id: 38,
    name: "The Derby Match Family Kitchen",
    category: "Family Restaurant",
    address: "7001 Holmes Rd",
    city: "Kansas City",
    state: "MO",
    lat: 38.9837,
    lng: -94.5592,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=7001+Holmes+Rd+Kansas+City",
    logo_url: venueImage("derby-match-kitchen"),
    opening_times: {
      monday: { open: "09:00", close: "21:00" },
      tuesday: { open: "09:00", close: "21:00" },
      wednesday: { open: "09:00", close: "21:00" },
      thursday: { open: "09:00", close: "22:00" },
      friday: { open: "09:00", close: "23:00" },
      saturday: { open: "08:00", close: "23:00" },
      sunday: { open: "08:00", close: "21:00" },
    },
  },
  {
    id: 39,
    name: "Winger's Pub & Pitch",
    category: "Pub",
    address: "3819 W 32nd Ave",
    city: "Denver",
    state: "CO",
    lat: 39.7548,
    lng: -105.0365,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=3819+W+32nd+Ave+Denver",
    logo_url: venueImage("wingers-pub"),
    opening_times: {
      monday: { open: "14:00", close: "00:00" },
      tuesday: { open: "14:00", close: "00:00" },
      wednesday: { open: "14:00", close: "00:00" },
      thursday: { open: "14:00", close: "01:00" },
      friday: { open: "13:00", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "23:00" },
    },
  },
  {
    id: 40,
    name: "Marcador Sports Bar",
    category: "Sports Bar",
    address: "1220 S Broad St",
    city: "Philadelphia",
    state: "PA",
    lat: 39.9329,
    lng: -75.1677,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1220+S+Broad+St+Philadelphia",
    logo_url: venueImage("marcador-bar"),
    opening_times: {
      monday: { open: "12:00", close: "00:00" },
      tuesday: { open: "12:00", close: "00:00" },
      wednesday: { open: "12:00", close: "00:00" },
      thursday: { open: "12:00", close: "01:00" },
      friday: { open: "12:00", close: "02:00" },
      saturday: { open: "10:00", close: "02:00" },
      sunday: { open: "10:00", close: "23:00" },
    },
  },
  {
    id: 41,
    name: "The Sideline Irish Bar",
    category: "Irish Bar",
    address: "411 S Main St",
    city: "St. Louis",
    state: "MO",
    lat: 38.6270,
    lng: -90.1994,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=411+S+Main+St+St.+Louis",
    logo_url: venueImage("sideline-irish"),
    opening_times: {
      monday: { open: "15:00", close: "01:00" },
      tuesday: { open: "15:00", close: "01:00" },
      wednesday: { open: "15:00", close: "01:00" },
      thursday: { open: "15:00", close: "02:00" },
      friday: { open: "14:00", close: "02:00" },
      saturday: { open: "12:00", close: "02:00" },
      sunday: { open: "12:00", close: "00:00" },
    },
  },
  {
    id: 42,
    name: "Curva Wing Co.",
    category: "Wing Joint",
    address: "3012 E 7th St",
    city: "Charlotte",
    state: "NC",
    lat: 35.2174,
    lng: -80.8162,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=3012+E+7th+St+Charlotte",
    logo_url: venueImage("curva-wings"),
    opening_times: {
      monday: { open: "11:00", close: "22:00" },
      tuesday: { open: "11:00", close: "22:00" },
      wednesday: { open: "11:00", close: "22:00" },
      thursday: { open: "11:00", close: "23:00" },
      friday: { open: "11:00", close: "00:00" },
      saturday: { open: "11:00", close: "00:00" },
      sunday: { open: "12:00", close: "21:00" },
    },
  },
  {
    id: 43,
    name: "Half-Volley Craft Coffee",
    category: "Cafe",
    address: "1744 Larimer St",
    city: "Denver",
    state: "CO",
    lat: 39.7525,
    lng: -104.9992,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1744+Larimer+St+Denver",
    logo_url: venueImage("half-volley-coffee"),
    opening_times: {
      monday: { open: "06:00", close: "16:00" },
      tuesday: { open: "06:00", close: "16:00" },
      wednesday: { open: "06:00", close: "16:00" },
      thursday: { open: "06:00", close: "17:00" },
      friday: { open: "06:00", close: "17:00" },
      saturday: { open: "07:00", close: "17:00" },
      sunday: { open: "07:00", close: "15:00" },
    },
  },
  {
    id: 44,
    name: "Counterattack Cocktail Bar",
    category: "Cocktail Bar",
    address: "875 W Peachtree St NW",
    city: "Atlanta",
    state: "GA",
    lat: 33.7845,
    lng: -84.3837,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=875+W+Peachtree+St+NW+Atlanta",
    logo_url: venueImage("counterattack-cocktails"),
    opening_times: {
      monday: { closed: true },
      tuesday: { open: "17:00", close: "01:00" },
      wednesday: { open: "17:00", close: "01:00" },
      thursday: { open: "17:00", close: "02:00" },
      friday: { open: "16:00", close: "02:00" },
      saturday: { open: "15:00", close: "02:00" },
      sunday: { open: "15:00", close: "00:00" },
    },
  },
  {
    id: 45,
    name: "Upper 90 American Grill",
    category: "American Grill",
    address: "700 Convention Center Dr",
    city: "Las Vegas",
    state: "NV",
    lat: 36.1254,
    lng: -115.1633,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=700+Convention+Center+Dr+Las+Vegas",
    logo_url: venueImage("upper-90-grill"),
    opening_times: {
      monday: { open: "11:00", close: "23:00" },
      tuesday: { open: "11:00", close: "23:00" },
      wednesday: { open: "11:00", close: "23:00" },
      thursday: { open: "11:00", close: "00:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "10:00", close: "02:00" },
      sunday: { open: "10:00", close: "23:00" },
    },
  },
  {
    id: 46,
    name: "The Bend It Brewery",
    category: "Brewery",
    address: "1420 NW Marshall St",
    city: "Portland",
    state: "OR",
    lat: 45.5269,
    lng: -122.6826,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1420+NW+Marshall+St+Portland",
    logo_url: venueImage("bend-it-brewery"),
    opening_times: {
      monday: { open: "13:00", close: "22:00" },
      tuesday: { open: "13:00", close: "22:00" },
      wednesday: { open: "13:00", close: "22:00" },
      thursday: { open: "13:00", close: "23:00" },
      friday: { open: "12:00", close: "00:00" },
      saturday: { open: "11:00", close: "00:00" },
      sunday: { open: "11:00", close: "22:00" },
    },
  },
  {
    id: 47,
    name: "La Liga Pizza",
    category: "Pizza Place",
    address: "529 King St W",
    city: "Toronto",
    state: "ON",
    lat: 43.6447,
    lng: -79.4003,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=529+King+St+W+Toronto",
    logo_url: venueImage("la-liga-pizza"),
    opening_times: {
      monday: { open: "11:30", close: "22:00" },
      tuesday: { open: "11:30", close: "22:00" },
      wednesday: { open: "11:30", close: "22:00" },
      thursday: { open: "11:30", close: "23:00" },
      friday: { open: "11:30", close: "00:00" },
      saturday: { open: "11:00", close: "00:00" },
      sunday: { open: "12:00", close: "21:00" },
    },
  },
  {
    id: 48,
    name: "Dead Ball Rooftop",
    category: "Rooftop",
    address: "4200 Park Ave",
    city: "Minneapolis",
    state: "MN",
    lat: 44.9599,
    lng: -93.2650,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=4200+Park+Ave+Minneapolis",
    logo_url: venueImage("dead-ball-rooftop"),
    opening_times: {
      monday: { closed: true },
      tuesday: { closed: true },
      wednesday: { open: "17:00", close: "23:00" },
      thursday: { open: "17:00", close: "23:00" },
      friday: { open: "15:00", close: "01:00" },
      saturday: { open: "13:00", close: "01:00" },
      sunday: { open: "13:00", close: "22:00" },
    },
  },
  {
    id: 49,
    name: "The Equalizer Pub",
    category: "Pub",
    address: "1201 N Calvert St",
    city: "Baltimore",
    state: "MD",
    lat: 39.3049,
    lng: -76.6128,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=1201+N+Calvert+St+Baltimore",
    logo_url: venueImage("equalizer-pub"),
    opening_times: {
      monday: { open: "14:00", close: "01:00" },
      tuesday: { open: "14:00", close: "01:00" },
      wednesday: { open: "14:00", close: "01:00" },
      thursday: { open: "14:00", close: "02:00" },
      friday: { open: "12:00", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "00:00" },
    },
  },
  {
    id: 50,
    name: "Extra Time Family Grill",
    category: "Family Restaurant",
    address: "840 Magazine St",
    city: "New Orleans",
    state: "LA",
    lat: 29.9390,
    lng: -90.0798,
    website: "https://example.com",
    maps_link: "https://maps.google.com/?q=840+Magazine+St+New+Orleans",
    logo_url: venueImage("extra-time-grill"),
    opening_times: {
      monday: { open: "09:00", close: "22:00" },
      tuesday: { open: "09:00", close: "22:00" },
      wednesday: { open: "09:00", close: "22:00" },
      thursday: { open: "09:00", close: "22:00" },
      friday: { open: "09:00", close: "23:00" },
      saturday: { open: "08:00", close: "23:00" },
      sunday: { open: "08:00", close: "21:00" },
    },
  },
  // ── Real NYC Venues ──────────────────────────────────────────────────────
  {
    id: 51,
    name: "Smithfield Hall",
    category: "Sports Bar",
    address: "138 W 25th St",
    city: "New York",
    state: "NY",
    lat: 40.7441,
    lng: -73.9928,
    website: "https://www.smithfieldhall.com",
    maps_link: "https://maps.google.com/?q=Smithfield+Hall+138+W+25th+St+New+York",
    logo_url: venueImage("smithfield-hall"),
    opening_times: {
      monday: { open: "11:30", close: "02:00" },
      tuesday: { open: "11:30", close: "02:00" },
      wednesday: { open: "11:30", close: "02:00" },
      thursday: { open: "11:30", close: "02:00" },
      friday: { open: "11:30", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 52,
    name: "Football Factory at Legends",
    category: "Sports Bar",
    address: "6 W 33rd St",
    city: "New York",
    state: "NY",
    lat: 40.7484,
    lng: -73.9856,
    website: "https://www.footballfactorynyc.com",
    maps_link: "https://maps.google.com/?q=Football+Factory+at+Legends+6+W+33rd+St+New+York",
    logo_url: venueImage("football-factory"),
    opening_times: {
      monday: { open: "11:00", close: "01:00" },
      tuesday: { open: "11:00", close: "01:00" },
      wednesday: { open: "11:00", close: "01:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "09:00", close: "02:00" },
      sunday: { open: "09:00", close: "01:00" },
    },
  },
  {
    id: 53,
    name: "Banter",
    category: "Pub",
    address: "132 Havemeyer St",
    city: "Brooklyn",
    state: "NY",
    lat: 40.7120,
    lng: -73.9571,
    website: "https://www.banterbrooklyn.com",
    maps_link: "https://maps.google.com/?q=Banter+132+Havemeyer+St+Brooklyn",
    logo_url: venueImage("banter-bk"),
    opening_times: {
      monday: { open: "12:00", close: "02:00" },
      tuesday: { open: "12:00", close: "02:00" },
      wednesday: { open: "12:00", close: "02:00" },
      thursday: { open: "12:00", close: "02:00" },
      friday: { open: "12:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 54,
    name: "The Blind Pig",
    category: "Pub",
    address: "233 E 14th St",
    city: "New York",
    state: "NY",
    lat: 40.7327,
    lng: -73.9847,
    website: "https://www.blindpignyc.com",
    maps_link: "https://maps.google.com/?q=The+Blind+Pig+233+E+14th+St+New+York",
    logo_url: venueImage("blind-pig-nyc"),
    opening_times: {
      monday: { open: "12:00", close: "02:00" },
      tuesday: { open: "12:00", close: "02:00" },
      wednesday: { open: "12:00", close: "02:00" },
      thursday: { open: "12:00", close: "02:00" },
      friday: { open: "12:00", close: "04:00" },
      saturday: { open: "11:00", close: "04:00" },
      sunday: { open: "11:00", close: "02:00" },
    },
  },
  {
    id: 55,
    name: "Woodwork",
    category: "Sports Bar",
    address: "583 Vanderbilt Ave",
    city: "Brooklyn",
    state: "NY",
    lat: 40.6808,
    lng: -73.9688,
    website: "https://www.woodworkbk.com",
    maps_link: "https://maps.google.com/?q=Woodwork+583+Vanderbilt+Ave+Brooklyn",
    logo_url: venueImage("woodwork-bk"),
    opening_times: {
      monday: { open: "16:00", close: "00:00" },
      tuesday: { open: "16:00", close: "00:00" },
      wednesday: { open: "16:00", close: "00:00" },
      thursday: { open: "16:00", close: "01:00" },
      friday: { open: "14:00", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "00:00" },
    },
  },
  {
    id: 56,
    name: "Stout NYC",
    category: "Irish Bar",
    address: "133 W 33rd St",
    city: "New York",
    state: "NY",
    lat: 40.7497,
    lng: -73.9909,
    website: "https://www.stoutnyc.com",
    maps_link: "https://maps.google.com/?q=Stout+NYC+133+W+33rd+St+New+York",
    logo_url: venueImage("stout-nyc"),
    opening_times: {
      monday: { open: "11:00", close: "02:00" },
      tuesday: { open: "11:00", close: "02:00" },
      wednesday: { open: "11:00", close: "02:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "04:00" },
      saturday: { open: "11:00", close: "04:00" },
      sunday: { open: "11:00", close: "02:00" },
    },
  },
  {
    id: 57,
    name: "The Irish Pub",
    category: "Irish Bar",
    address: "837 7th Ave",
    city: "New York",
    state: "NY",
    lat: 40.7618,
    lng: -73.9815,
    website: "https://www.irishpubnyc.com",
    maps_link: "https://maps.google.com/?q=The+Irish+Pub+837+7th+Ave+New+York",
    logo_url: venueImage("irish-pub-nyc"),
    opening_times: {
      monday: { open: "10:00", close: "02:00" },
      tuesday: { open: "10:00", close: "02:00" },
      wednesday: { open: "10:00", close: "02:00" },
      thursday: { open: "10:00", close: "02:00" },
      friday: { open: "10:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 58,
    name: "Feile",
    category: "Irish Bar",
    address: "131 W 33rd St",
    city: "New York",
    state: "NY",
    lat: 40.7496,
    lng: -73.9907,
    website: "https://www.feilenyc.com",
    maps_link: "https://maps.google.com/?q=Feile+131+W+33rd+St+New+York",
    logo_url: venueImage("feile-nyc"),
    opening_times: {
      monday: { open: "11:00", close: "02:00" },
      tuesday: { open: "11:00", close: "02:00" },
      wednesday: { open: "11:00", close: "02:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 59,
    name: "Legends Bar",
    category: "Sports Bar",
    address: "6 W 33rd St 2nd Fl",
    city: "New York",
    state: "NY",
    lat: 40.7485,
    lng: -73.9857,
    website: "https://www.legendsbarnyc.com",
    maps_link: "https://maps.google.com/?q=Legends+Bar+6+W+33rd+St+New+York",
    logo_url: venueImage("legends-bar"),
    opening_times: {
      monday: { open: "11:30", close: "01:00" },
      tuesday: { open: "11:30", close: "01:00" },
      wednesday: { open: "11:30", close: "01:00" },
      thursday: { open: "11:30", close: "02:00" },
      friday: { open: "11:30", close: "02:00" },
      saturday: { open: "10:00", close: "02:00" },
      sunday: { open: "10:00", close: "01:00" },
    },
  },
  {
    id: 60,
    name: "Blarney Stone Pub",
    category: "Irish Bar",
    address: "710 8th Ave",
    city: "New York",
    state: "NY",
    lat: 40.7589,
    lng: -73.9897,
    website: "https://www.blarneystonepub.com",
    maps_link: "https://maps.google.com/?q=Blarney+Stone+Pub+710+8th+Ave+New+York",
    logo_url: venueImage("blarney-stone"),
    opening_times: {
      monday: { open: "08:00", close: "02:00" },
      tuesday: { open: "08:00", close: "02:00" },
      wednesday: { open: "08:00", close: "02:00" },
      thursday: { open: "08:00", close: "02:00" },
      friday: { open: "08:00", close: "04:00" },
      saturday: { open: "08:00", close: "04:00" },
      sunday: { open: "08:00", close: "02:00" },
    },
  },
  {
    id: 61,
    name: "Professor Thom's",
    category: "Pub",
    address: "219 2nd Ave",
    city: "New York",
    state: "NY",
    lat: 40.7316,
    lng: -73.9859,
    website: "https://www.professorthoms.com",
    maps_link: "https://maps.google.com/?q=Professor+Thoms+219+2nd+Ave+New+York",
    logo_url: venueImage("professor-thoms"),
    opening_times: {
      monday: { open: "12:00", close: "02:00" },
      tuesday: { open: "12:00", close: "02:00" },
      wednesday: { open: "12:00", close: "02:00" },
      thursday: { open: "12:00", close: "02:00" },
      friday: { open: "12:00", close: "04:00" },
      saturday: { open: "11:00", close: "04:00" },
      sunday: { open: "11:00", close: "02:00" },
    },
  },
  {
    id: 62,
    name: "Carragher's",
    category: "Sports Bar",
    address: "228 W 39th St",
    city: "New York",
    state: "NY",
    lat: 40.7546,
    lng: -73.9901,
    website: "https://www.carraghersnyc.com",
    maps_link: "https://maps.google.com/?q=Carraghers+228+W+39th+St+New+York",
    logo_url: venueImage("carraghers"),
    opening_times: {
      monday: { open: "11:00", close: "02:00" },
      tuesday: { open: "11:00", close: "02:00" },
      wednesday: { open: "11:00", close: "02:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "04:00" },
      saturday: { open: "09:00", close: "04:00" },
      sunday: { open: "09:00", close: "02:00" },
    },
  },
  {
    id: 63,
    name: "Berry Park",
    category: "Rooftop",
    address: "4 Berry St",
    city: "Brooklyn",
    state: "NY",
    lat: 40.7177,
    lng: -73.9619,
    website: "https://www.berryparkbk.com",
    maps_link: "https://maps.google.com/?q=Berry+Park+4+Berry+St+Brooklyn",
    logo_url: venueImage("berry-park"),
    opening_times: {
      monday: { open: "14:00", close: "00:00" },
      tuesday: { open: "14:00", close: "00:00" },
      wednesday: { open: "14:00", close: "00:00" },
      thursday: { open: "14:00", close: "01:00" },
      friday: { open: "14:00", close: "02:00" },
      saturday: { open: "12:00", close: "02:00" },
      sunday: { open: "12:00", close: "00:00" },
    },
  },
  {
    id: 64,
    name: "Hudson Station Bar & Grill",
    category: "American Grill",
    address: "440 9th Ave",
    city: "New York",
    state: "NY",
    lat: 40.7538,
    lng: -73.9965,
    website: "https://www.hudsonstationnyc.com",
    maps_link: "https://maps.google.com/?q=Hudson+Station+Bar+440+9th+Ave+New+York",
    logo_url: venueImage("hudson-station"),
    opening_times: {
      monday: { open: "11:00", close: "00:00" },
      tuesday: { open: "11:00", close: "00:00" },
      wednesday: { open: "11:00", close: "00:00" },
      thursday: { open: "11:00", close: "01:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "10:00", close: "02:00" },
      sunday: { open: "10:00", close: "00:00" },
    },
  },
  {
    id: 65,
    name: "Keg & Lantern Brewing",
    category: "Brewery",
    address: "97 Nassau Ave",
    city: "Brooklyn",
    state: "NY",
    lat: 40.7235,
    lng: -73.9513,
    website: "https://www.kegandlantern.com",
    maps_link: "https://maps.google.com/?q=Keg+and+Lantern+Brewing+97+Nassau+Ave+Brooklyn",
    logo_url: venueImage("keg-lantern"),
    opening_times: {
      monday: { open: "15:00", close: "23:00" },
      tuesday: { open: "15:00", close: "23:00" },
      wednesday: { open: "15:00", close: "23:00" },
      thursday: { open: "15:00", close: "00:00" },
      friday: { open: "12:00", close: "01:00" },
      saturday: { open: "12:00", close: "01:00" },
      sunday: { open: "12:00", close: "22:00" },
    },
  },
  {
    id: 66,
    name: "Bua",
    category: "Pub",
    address: "122 St Marks Pl",
    city: "New York",
    state: "NY",
    lat: 40.7280,
    lng: -73.9842,
    website: "https://www.buabar.com",
    maps_link: "https://maps.google.com/?q=Bua+122+St+Marks+Pl+New+York",
    logo_url: venueImage("bua-bar"),
    opening_times: {
      monday: { open: "14:00", close: "02:00" },
      tuesday: { open: "14:00", close: "02:00" },
      wednesday: { open: "14:00", close: "02:00" },
      thursday: { open: "14:00", close: "02:00" },
      friday: { open: "14:00", close: "04:00" },
      saturday: { open: "12:00", close: "04:00" },
      sunday: { open: "12:00", close: "02:00" },
    },
  },
  {
    id: 67,
    name: "Amity Hall",
    category: "Sports Bar",
    address: "80 W 3rd St",
    city: "New York",
    state: "NY",
    lat: 40.7299,
    lng: -73.9989,
    website: "https://www.amityhallnyc.com",
    maps_link: "https://maps.google.com/?q=Amity+Hall+80+W+3rd+St+New+York",
    logo_url: venueImage("amity-hall"),
    opening_times: {
      monday: { open: "11:30", close: "01:00" },
      tuesday: { open: "11:30", close: "01:00" },
      wednesday: { open: "11:30", close: "01:00" },
      thursday: { open: "11:30", close: "02:00" },
      friday: { open: "11:30", close: "02:00" },
      saturday: { open: "10:00", close: "02:00" },
      sunday: { open: "10:00", close: "01:00" },
    },
  },
  {
    id: 68,
    name: "Village Pourhouse",
    category: "Sports Bar",
    address: "982 3rd Ave",
    city: "New York",
    state: "NY",
    lat: 40.7584,
    lng: -73.9665,
    website: "https://www.villagepourhouse.com",
    maps_link: "https://maps.google.com/?q=Village+Pourhouse+982+3rd+Ave+New+York",
    logo_url: venueImage("village-pourhouse"),
    opening_times: {
      monday: { open: "11:00", close: "02:00" },
      tuesday: { open: "11:00", close: "02:00" },
      wednesday: { open: "11:00", close: "02:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 69,
    name: "Standings Bar",
    category: "Sports Bar",
    address: "43 E 7th St",
    city: "New York",
    state: "NY",
    lat: 40.7274,
    lng: -73.9884,
    website: "https://www.standingsbar.com",
    maps_link: "https://maps.google.com/?q=Standings+Bar+43+E+7th+St+New+York",
    logo_url: venueImage("standings-bar"),
    opening_times: {
      monday: { open: "12:00", close: "02:00" },
      tuesday: { open: "12:00", close: "02:00" },
      wednesday: { open: "12:00", close: "02:00" },
      thursday: { open: "12:00", close: "02:00" },
      friday: { open: "12:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 70,
    name: "Kinsale Tavern",
    category: "Irish Bar",
    address: "1672 3rd Ave",
    city: "New York",
    state: "NY",
    lat: 40.7818,
    lng: -73.9517,
    website: "https://www.kinsaletavern.com",
    maps_link: "https://maps.google.com/?q=Kinsale+Tavern+1672+3rd+Ave+New+York",
    logo_url: venueImage("kinsale-tavern"),
    opening_times: {
      monday: { open: "11:00", close: "02:00" },
      tuesday: { open: "11:00", close: "02:00" },
      wednesday: { open: "11:00", close: "02:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 71,
    name: "Riviera Cafe & Sports Bar",
    category: "Sports Bar",
    address: "225 W 4th St",
    city: "New York",
    state: "NY",
    lat: 40.7335,
    lng: -74.0013,
    website: "https://www.rivieracafeny.com",
    maps_link: "https://maps.google.com/?q=Riviera+Cafe+225+W+4th+St+New+York",
    logo_url: venueImage("riviera-cafe"),
    opening_times: {
      monday: { open: "11:00", close: "02:00" },
      tuesday: { open: "11:00", close: "02:00" },
      wednesday: { open: "11:00", close: "02:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 72,
    name: "Tir Na Nog",
    category: "Irish Bar",
    address: "315 W 39th St",
    city: "New York",
    state: "NY",
    lat: 40.7561,
    lng: -73.9927,
    website: "https://www.tirnanognyc.com",
    maps_link: "https://maps.google.com/?q=Tir+Na+Nog+315+W+39th+St+New+York",
    logo_url: venueImage("tir-na-nog"),
    opening_times: {
      monday: { open: "11:30", close: "01:00" },
      tuesday: { open: "11:30", close: "01:00" },
      wednesday: { open: "11:30", close: "01:00" },
      thursday: { open: "11:30", close: "02:00" },
      friday: { open: "11:30", close: "04:00" },
      saturday: { open: "11:00", close: "04:00" },
      sunday: { open: "11:00", close: "01:00" },
    },
  },
  {
    id: 73,
    name: "The Mean Fiddler",
    category: "Irish Bar",
    address: "266 W 47th St",
    city: "New York",
    state: "NY",
    lat: 40.7600,
    lng: -73.9873,
    website: "https://www.meanfiddlernyc.com",
    maps_link: "https://maps.google.com/?q=The+Mean+Fiddler+266+W+47th+St+New+York",
    logo_url: venueImage("mean-fiddler"),
    opening_times: {
      monday: { open: "11:00", close: "02:00" },
      tuesday: { open: "11:00", close: "02:00" },
      wednesday: { open: "11:00", close: "02:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 74,
    name: "Mulligan's Pub",
    category: "Irish Bar",
    address: "267 Madison Ave",
    city: "New York",
    state: "NY",
    lat: 40.7505,
    lng: -73.9800,
    website: "https://www.mulliganspubnyc.com",
    maps_link: "https://maps.google.com/?q=Mulligans+Pub+267+Madison+Ave+New+York",
    logo_url: venueImage("mulligans-pub"),
    opening_times: {
      monday: { open: "11:00", close: "01:00" },
      tuesday: { open: "11:00", close: "01:00" },
      wednesday: { open: "11:00", close: "01:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "01:00" },
    },
  },
  {
    id: 75,
    name: "Bronx Alehouse",
    category: "Pub",
    address: "216 W 238th St",
    city: "Bronx",
    state: "NY",
    lat: 40.8852,
    lng: -73.9040,
    website: "https://www.bronxalehouse.com",
    maps_link: "https://maps.google.com/?q=Bronx+Alehouse+216+W+238th+St+Bronx",
    logo_url: venueImage("bronx-alehouse"),
    opening_times: {
      monday: { open: "12:00", close: "00:00" },
      tuesday: { open: "12:00", close: "00:00" },
      wednesday: { open: "12:00", close: "00:00" },
      thursday: { open: "12:00", close: "01:00" },
      friday: { open: "12:00", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "00:00" },
    },
  },
  {
    id: 76,
    name: "Jack Demsey's",
    category: "Sports Bar",
    address: "36 W 33rd St",
    city: "New York",
    state: "NY",
    lat: 40.7488,
    lng: -73.9873,
    website: "https://www.jackdempseys.com",
    maps_link: "https://maps.google.com/?q=Jack+Dempseys+36+W+33rd+St+New+York",
    logo_url: venueImage("jack-dempseys"),
    opening_times: {
      monday: { open: "11:00", close: "02:00" },
      tuesday: { open: "11:00", close: "02:00" },
      wednesday: { open: "11:00", close: "02:00" },
      thursday: { open: "11:00", close: "02:00" },
      friday: { open: "11:00", close: "04:00" },
      saturday: { open: "10:00", close: "04:00" },
      sunday: { open: "10:00", close: "02:00" },
    },
  },
  {
    id: 77,
    name: "Hispaniola",
    category: "Mexican",
    address: "839 Jackson Ave",
    city: "Bronx",
    state: "NY",
    lat: 40.8181,
    lng: -73.9091,
    website: "https://www.hispaniolanyc.com",
    maps_link: "https://maps.google.com/?q=Hispaniola+839+Jackson+Ave+Bronx",
    logo_url: venueImage("hispaniola-bx"),
    opening_times: {
      monday: { open: "12:00", close: "23:00" },
      tuesday: { open: "12:00", close: "23:00" },
      wednesday: { open: "12:00", close: "23:00" },
      thursday: { open: "12:00", close: "00:00" },
      friday: { open: "12:00", close: "01:00" },
      saturday: { open: "11:00", close: "01:00" },
      sunday: { open: "11:00", close: "22:00" },
    },
  },
  {
    id: 78,
    name: "Clinton Hall",
    category: "American Grill",
    address: "90 Washington St",
    city: "New York",
    state: "NY",
    lat: 40.7091,
    lng: -74.0143,
    website: "https://www.clintonhallny.com",
    maps_link: "https://maps.google.com/?q=Clinton+Hall+90+Washington+St+New+York",
    logo_url: venueImage("clinton-hall"),
    opening_times: {
      monday: { open: "11:30", close: "00:00" },
      tuesday: { open: "11:30", close: "00:00" },
      wednesday: { open: "11:30", close: "00:00" },
      thursday: { open: "11:30", close: "01:00" },
      friday: { open: "11:30", close: "02:00" },
      saturday: { open: "11:00", close: "02:00" },
      sunday: { open: "11:00", close: "00:00" },
    },
  },
  {
    id: 79,
    name: "Astoria Bier & Cheese",
    category: "Brewery",
    address: "34-14 Broadway",
    city: "Astoria",
    state: "NY",
    lat: 40.7629,
    lng: -73.9183,
    website: "https://www.astoriabierandcheese.com",
    maps_link: "https://maps.google.com/?q=Astoria+Bier+and+Cheese+34-14+Broadway+Astoria",
    logo_url: venueImage("astoria-bier"),
    opening_times: {
      monday: { open: "12:00", close: "23:00" },
      tuesday: { open: "12:00", close: "23:00" },
      wednesday: { open: "12:00", close: "23:00" },
      thursday: { open: "12:00", close: "00:00" },
      friday: { open: "12:00", close: "01:00" },
      saturday: { open: "11:00", close: "01:00" },
      sunday: { open: "11:00", close: "22:00" },
    },
  },
  {
    id: 80,
    name: "230 Fifth Rooftop Bar",
    category: "Rooftop",
    address: "230 5th Ave",
    city: "New York",
    state: "NY",
    lat: 40.7437,
    lng: -73.9878,
    website: "https://www.230-fifth.com",
    maps_link: "https://maps.google.com/?q=230+Fifth+Rooftop+Bar+230+5th+Ave+New+York",
    logo_url: venueImage("230-fifth"),
    opening_times: {
      monday: { open: "16:00", close: "02:00" },
      tuesday: { open: "16:00", close: "02:00" },
      wednesday: { open: "16:00", close: "02:00" },
      thursday: { open: "16:00", close: "02:00" },
      friday: { open: "14:00", close: "04:00" },
      saturday: { open: "12:00", close: "04:00" },
      sunday: { open: "12:00", close: "02:00" },
    },
  },
]

// Full tournament schedule grouped by round
export const tournamentSchedule = [
  {
    round: "Group Stage - Day 1",
    games: [
      { id: 1, date: "Jun 11", time: "15:00", teamA: "Mexico", teamB: "South Africa", flagA: "🇲🇽", flagB: "🇿🇦", venue: "Estadio Azteca, Mexico City", group: "A" },
      { id: 2, date: "Jun 11", time: "22:00", teamA: "South Korea", teamB: "PO1", flagA: "🇰🇷", flagB: "🏳️", venue: "Estadio Akron, Zapopan", group: "A" },
    ],
  },
  {
    round: "Group Stage - Day 2",
    games: [
      { id: 3, date: "Jun 12", time: "15:00", teamA: "Canada", teamB: "PO2", flagA: "🇨🇦", flagB: "🏳️", venue: "BMO Field, Toronto", group: "B" },
      { id: 4, date: "Jun 12", time: "21:00", teamA: "USA", teamB: "Paraguay", flagA: "🇺🇸", flagB: "🇵🇾", venue: "SoFi Stadium, Los Angeles", group: "D" },
    ],
  },
  {
    round: "Group Stage - Day 3",
    games: [
      { id: 5, date: "Jun 13", time: "15:00", teamA: "Qatar", teamB: "Switzerland", flagA: "🇶🇦", flagB: "🇨🇭", venue: "Levi's Stadium, Santa Clara", group: "B" },
      { id: 6, date: "Jun 13", time: "18:00", teamA: "Brazil", teamB: "Morocco", flagA: "🇧🇷", flagB: "🇲🇦", venue: "MetLife Stadium, New Jersey", group: "C" },
      { id: 7, date: "Jun 13", time: "21:00", teamA: "Haiti", teamB: "Scotland", flagA: "🇭🇹", flagB: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", venue: "Gillette Stadium, Foxborough", group: "C" },
    ],
  },
  {
    round: "Group Stage - Day 4",
    games: [
      { id: 8, date: "Jun 14", time: "00:00", teamA: "Australia", teamB: "PO3", flagA: "🇦🇺", flagB: "🏳️", venue: "BC Place, Vancouver", group: "D" },
      { id: 9, date: "Jun 14", time: "13:00", teamA: "Germany", teamB: "Curacao", flagA: "🇩🇪", flagB: "🇨🇼", venue: "NRG Stadium, Houston", group: "E" },
      { id: 10, date: "Jun 14", time: "16:00", teamA: "Netherlands", teamB: "Japan", flagA: "🇳🇱", flagB: "🇯🇵", venue: "AT&T Stadium, Arlington", group: "F" },
      { id: 11, date: "Jun 14", time: "19:00", teamA: "Ivory Coast", teamB: "Ecuador", flagA: "🇨🇮", flagB: "🇪🇨", venue: "Lincoln Financial Field, Philadelphia", group: "E" },
      { id: 12, date: "Jun 14", time: "22:00", teamA: "PO4", teamB: "Tunisia", flagA: "🏳️", flagB: "🇹🇳", venue: "Estadio BBVA, Monterrey", group: "F" },
    ],
  },
  {
    round: "Group Stage - Day 5",
    games: [
      { id: 13, date: "Jun 15", time: "12:00", teamA: "Spain", teamB: "Cape Verde", flagA: "🇪🇸", flagB: "🇨🇻", venue: "Mercedes-Benz Stadium, Atlanta", group: "H" },
      { id: 14, date: "Jun 15", time: "15:00", teamA: "Belgium", teamB: "Egypt", flagA: "🇧🇪", flagB: "🇪🇬", venue: "Lumen Field, Seattle", group: "G" },
      { id: 15, date: "Jun 15", time: "18:00", teamA: "Saudi Arabia", teamB: "Uruguay", flagA: "🇸🇦", flagB: "🇺🇾", venue: "Hard Rock Stadium, Miami", group: "H" },
      { id: 16, date: "Jun 15", time: "21:00", teamA: "Iran", teamB: "New Zealand", flagA: "🇮🇷", flagB: "🇳🇿", venue: "SoFi Stadium, Los Angeles", group: "G" },
    ],
  },
  {
    round: "Group Stage - Day 6",
    games: [
      { id: 17, date: "Jun 16", time: "15:00", teamA: "France", teamB: "Senegal", flagA: "🇫🇷", flagB: "🇸🇳", venue: "MetLife Stadium, New Jersey", group: "I" },
      { id: 18, date: "Jun 16", time: "18:00", teamA: "PO5", teamB: "Norway", flagA: "🏳️", flagB: "🇳🇴", venue: "Gillette Stadium, Foxborough", group: "I" },
      { id: 19, date: "Jun 16", time: "21:00", teamA: "Argentina", teamB: "Algeria", flagA: "🇦🇷", flagB: "🇩🇿", venue: "Arrowhead Stadium, Kansas City", group: "J" },
    ],
  },
  {
    round: "Group Stage - Day 7",
    games: [
      { id: 20, date: "Jun 17", time: "00:00", teamA: "Austria", teamB: "Jordan", flagA: "🇦🇹", flagB: "🇯🇴", venue: "Levi's Stadium, Santa Clara", group: "J" },
      { id: 21, date: "Jun 17", time: "13:00", teamA: "Portugal", teamB: "PO6", flagA: "🇵🇹", flagB: "🏳️", venue: "NRG Stadium, Houston", group: "K" },
      { id: 22, date: "Jun 17", time: "16:00", teamA: "England", teamB: "Croatia", flagA: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", flagB: "🇭🇷", venue: "AT&T Stadium, Arlington", group: "L" },
      { id: 23, date: "Jun 17", time: "19:00", teamA: "Ghana", teamB: "Panama", flagA: "🇬🇭", flagB: "🇵🇦", venue: "BMO Field, Toronto", group: "L" },
      { id: 24, date: "Jun 17", time: "22:00", teamA: "Uzbekistan", teamB: "Colombia", flagA: "🇺🇿", flagB: "🇨🇴", venue: "Estadio Azteca, Mexico City", group: "K" },
    ],
  },
  {
    round: "Group Stage - Day 8",
    games: [
      { id: 25, date: "Jun 18", time: "12:00", teamA: "PO1", teamB: "South Africa", flagA: "🏳️", flagB: "🇿🇦", venue: "Mercedes-Benz Stadium, Atlanta", group: "A" },
      { id: 26, date: "Jun 18", time: "15:00", teamA: "Switzerland", teamB: "PO2", flagA: "🇨🇭", flagB: "🏳️", venue: "SoFi Stadium, Los Angeles", group: "B" },
      { id: 27, date: "Jun 18", time: "18:00", teamA: "Canada", teamB: "Qatar", flagA: "🇨🇦", flagB: "🇶🇦", venue: "BC Place, Vancouver", group: "B" },
      { id: 28, date: "Jun 18", time: "21:00", teamA: "Mexico", teamB: "South Korea", flagA: "🇲🇽", flagB: "🇰🇷", venue: "Estadio Akron, Zapopan", group: "A" },
    ],
  },
  {
    round: "Group Stage - Day 9",
    games: [
      { id: 29, date: "Jun 19", time: "15:00", teamA: "USA", teamB: "Australia", flagA: "🇺🇸", flagB: "🇦🇺", venue: "Lumen Field, Seattle", group: "D" },
      { id: 30, date: "Jun 19", time: "18:00", teamA: "Scotland", teamB: "Morocco", flagA: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", flagB: "🇲🇦", venue: "Gillette Stadium, Foxborough", group: "C" },
      { id: 31, date: "Jun 19", time: "21:00", teamA: "Brazil", teamB: "Haiti", flagA: "🇧🇷", flagB: "🇭🇹", venue: "Lincoln Financial Field, Philadelphia", group: "C" },
    ],
  },
  {
    round: "Group Stage - Day 10",
    games: [
      { id: 32, date: "Jun 20", time: "00:00", teamA: "PO3", teamB: "Paraguay", flagA: "🏳️", flagB: "🇵🇾", venue: "Levi's Stadium, Santa Clara", group: "D" },
      { id: 33, date: "Jun 20", time: "13:00", teamA: "Netherlands", teamB: "PO4", flagA: "🇳🇱", flagB: "🏳️", venue: "NRG Stadium, Houston", group: "F" },
      { id: 34, date: "Jun 20", time: "16:00", teamA: "Germany", teamB: "Ivory Coast", flagA: "🇩🇪", flagB: "🇨🇮", venue: "BMO Field, Toronto", group: "E" },
      { id: 35, date: "Jun 20", time: "20:00", teamA: "Ecuador", teamB: "Curacao", flagA: "🇪🇨", flagB: "🇨🇼", venue: "Arrowhead Stadium, Kansas City", group: "E" },
    ],
  },
  {
    round: "Group Stage - Day 11",
    games: [
      { id: 36, date: "Jun 21", time: "00:00", teamA: "Tunisia", teamB: "Japan", flagA: "🇹🇳", flagB: "🇯🇵", venue: "Estadio BBVA, Monterrey", group: "F" },
      { id: 37, date: "Jun 21", time: "12:00", teamA: "Spain", teamB: "Saudi Arabia", flagA: "🇪🇸", flagB: "🇸🇦", venue: "Mercedes-Benz Stadium, Atlanta", group: "H" },
      { id: 38, date: "Jun 21", time: "15:00", teamA: "Belgium", teamB: "Iran", flagA: "🇧🇪", flagB: "🇮🇷", venue: "SoFi Stadium, Los Angeles", group: "G" },
      { id: 39, date: "Jun 21", time: "18:00", teamA: "Uruguay", teamB: "Cape Verde", flagA: "🇺🇾", flagB: "🇨🇻", venue: "Hard Rock Stadium, Miami", group: "H" },
      { id: 40, date: "Jun 21", time: "21:00", teamA: "New Zealand", teamB: "Egypt", flagA: "🇳🇿", flagB: "🇪🇬", venue: "BC Place, Vancouver", group: "G" },
    ],
  },
  {
    round: "Group Stage - Day 12",
    games: [
      { id: 41, date: "Jun 22", time: "13:00", teamA: "Argentina", teamB: "Austria", flagA: "🇦🇷", flagB: "🇦🇹", venue: "AT&T Stadium, Arlington", group: "J" },
      { id: 42, date: "Jun 22", time: "17:00", teamA: "France", teamB: "PO5", flagA: "🇫🇷", flagB: "🏳️", venue: "Lincoln Financial Field, Philadelphia", group: "I" },
      { id: 43, date: "Jun 22", time: "20:00", teamA: "Norway", teamB: "Senegal", flagA: "🇳🇴", flagB: "🇸🇳", venue: "BMO Field, Toronto", group: "I" },
      { id: 44, date: "Jun 22", time: "23:00", teamA: "Jordan", teamB: "Algeria", flagA: "🇯🇴", flagB: "🇩🇿", venue: "Levi's Stadium, Santa Clara", group: "J" },
    ],
  },
  {
    round: "Group Stage - Day 13",
    games: [
      { id: 45, date: "Jun 23", time: "13:00", teamA: "Portugal", teamB: "Uzbekistan", flagA: "🇵🇹", flagB: "🇺🇿", venue: "NRG Stadium, Houston", group: "K" },
      { id: 46, date: "Jun 23", time: "16:00", teamA: "England", teamB: "Ghana", flagA: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", flagB: "🇬🇭", venue: "Gillette Stadium, Foxborough", group: "L" },
      { id: 47, date: "Jun 23", time: "19:00", teamA: "Panama", teamB: "Croatia", flagA: "🇵🇦", flagB: "🇭🇷", venue: "Gillette Stadium, Foxborough", group: "L" },
      { id: 48, date: "Jun 23", time: "22:00", teamA: "Colombia", teamB: "PO6", flagA: "🇨🇴", flagB: "🏳️", venue: "Estadio Akron, Zapopan", group: "K" },
    ],
  },
  {
    round: "Group Stage - Day 14",
    games: [
      { id: 49, date: "Jun 24", time: "15:00", teamA: "Switzerland", teamB: "Canada", flagA: "🇨🇭", flagB: "🇨🇦", venue: "BC Place, Vancouver", group: "B" },
      { id: 50, date: "Jun 24", time: "15:00", teamA: "PO2", teamB: "Qatar", flagA: "🏳️", flagB: "🇶🇦", venue: "Lumen Field, Seattle", group: "B" },
      { id: 51, date: "Jun 24", time: "18:00", teamA: "Morocco", teamB: "Haiti", flagA: "🇲🇦", flagB: "🇭🇹", venue: "Mercedes-Benz Stadium, Atlanta", group: "C" },
      { id: 52, date: "Jun 24", time: "18:00", teamA: "Scotland", teamB: "Brazil", flagA: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", flagB: "🇧🇷", venue: "Hard Rock Stadium, Miami", group: "C" },
      { id: 53, date: "Jun 24", time: "21:00", teamA: "South Africa", teamB: "South Korea", flagA: "🇿🇦", flagB: "🇰🇷", venue: "Estadio BBVA, Monterrey", group: "A" },
      { id: 54, date: "Jun 24", time: "21:00", teamA: "PO1", teamB: "Mexico", flagA: "🏳️", flagB: "🇲🇽", venue: "Estadio Azteca, Mexico City", group: "A" },
    ],
  },
  {
    round: "Group Stage - Day 15",
    games: [
      { id: 55, date: "Jun 25", time: "16:00", teamA: "Curacao", teamB: "Ivory Coast", flagA: "🇨🇼", flagB: "🇨🇮", venue: "Lincoln Financial Field, Philadelphia", group: "E" },
      { id: 56, date: "Jun 25", time: "16:00", teamA: "Ecuador", teamB: "Germany", flagA: "🇪🇨", flagB: "🇩🇪", venue: "MetLife Stadium, New Jersey", group: "E" },
      { id: 57, date: "Jun 25", time: "19:00", teamA: "Tunisia", teamB: "Netherlands", flagA: "🇹🇳", flagB: "🇳🇱", venue: "Arrowhead Stadium, Kansas City", group: "F" },
      { id: 58, date: "Jun 25", time: "19:00", teamA: "Japan", teamB: "PO4", flagA: "🇯🇵", flagB: "🏳️", venue: "AT&T Stadium, Arlington", group: "F" },
      { id: 59, date: "Jun 25", time: "22:00", teamA: "PO3", teamB: "USA", flagA: "🏳️", flagB: "🇺🇸", venue: "SoFi Stadium, Los Angeles", group: "D" },
      { id: 60, date: "Jun 25", time: "22:00", teamA: "Paraguay", teamB: "Australia", flagA: "🇵🇾", flagB: "🇦🇺", venue: "Levi's Stadium, Santa Clara", group: "D" },
    ],
  },
  {
    round: "Group Stage - Day 16",
    games: [
      { id: 61, date: "Jun 26", time: "15:00", teamA: "Norway", teamB: "France", flagA: "🇳🇴", flagB: "🇫🇷", venue: "Gillette Stadium, Foxborough", group: "I" },
      { id: 62, date: "Jun 26", time: "15:00", teamA: "Senegal", teamB: "PO5", flagA: "🇸🇳", flagB: "🏳️", venue: "BMO Field, Toronto", group: "I" },
      { id: 63, date: "Jun 26", time: "20:00", teamA: "Cape Verde", teamB: "Saudi Arabia", flagA: "🇨🇻", flagB: "🇸🇦", venue: "NRG Stadium, Houston", group: "H" },
      { id: 64, date: "Jun 26", time: "20:00", teamA: "Uruguay", teamB: "Spain", flagA: "🇺🇾", flagB: "🇪🇸", venue: "Estadio Akron, Zapopan", group: "H" },
      { id: 65, date: "Jun 26", time: "23:00", teamA: "New Zealand", teamB: "Belgium", flagA: "🇳🇿", flagB: "🇧🇪", venue: "BC Place, Vancouver", group: "G" },
      { id: 66, date: "Jun 26", time: "23:00", teamA: "Egypt", teamB: "Iran", flagA: "🇪🇬", flagB: "🇮🇷", venue: "Lumen Field, Seattle", group: "G" },
    ],
  },
  {
    round: "Group Stage - Day 17",
    games: [
      { id: 67, date: "Jun 27", time: "17:00", teamA: "Panama", teamB: "England", flagA: "🇵🇦", flagB: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", venue: "MetLife Stadium, New Jersey", group: "L" },
      { id: 68, date: "Jun 27", time: "17:00", teamA: "Croatia", teamB: "Ghana", flagA: "🇭🇷", flagB: "🇬🇭", venue: "Lincoln Financial Field, Philadelphia", group: "L" },
      { id: 69, date: "Jun 27", time: "19:30", teamA: "Colombia", teamB: "Portugal", flagA: "🇨🇴", flagB: "🇵🇹", venue: "Hard Rock Stadium, Miami", group: "K" },
      { id: 70, date: "Jun 27", time: "19:30", teamA: "PO6", teamB: "Uzbekistan", flagA: "🏳️", flagB: "🇺🇿", venue: "Mercedes-Benz Stadium, Atlanta", group: "K" },
      { id: 71, date: "Jun 27", time: "22:00", teamA: "Algeria", teamB: "Austria", flagA: "🇩🇿", flagB: "🇦🇹", venue: "Arrowhead Stadium, Kansas City", group: "J" },
      { id: 72, date: "Jun 27", time: "22:00", teamA: "Jordan", teamB: "Argentina", flagA: "🇯🇴", flagB: "🇦🇷", venue: "AT&T Stadium, Arlington", group: "J" },
    ],
  },
  {
    round: "Round of 32",
    games: [
      { id: 73, date: "Jun 28", time: "15:00", teamA: "2A", teamB: "2B", flagA: "🏳️", flagB: "🏳️", venue: "SoFi Stadium, Los Angeles", group: "R32" },
      { id: 76, date: "Jun 29", time: "13:00", teamA: "1C", teamB: "2F", flagA: "🏳️", flagB: "🏳️", venue: "NRG Stadium, Houston", group: "R32" },
      { id: 74, date: "Jun 29", time: "16:30", teamA: "1E", teamB: "3rd", flagA: "🏳️", flagB: "🏳️", venue: "Gillette Stadium, Foxborough", group: "R32" },
      { id: 75, date: "Jun 29", time: "21:00", teamA: "1F", teamB: "2C", flagA: "🏳️", flagB: "🏳️", venue: "Estadio BBVA, Monterrey", group: "R32" },
      { id: 78, date: "Jun 30", time: "13:00", teamA: "2E", teamB: "2I", flagA: "🏳️", flagB: "🏳️", venue: "AT&T Stadium, Arlington", group: "R32" },
      { id: 77, date: "Jun 30", time: "17:00", teamA: "1I", teamB: "3rd", flagA: "🏳️", flagB: "🏳️", venue: "MetLife Stadium, New Jersey", group: "R32" },
      { id: 79, date: "Jun 30", time: "21:00", teamA: "1A", teamB: "3rd", flagA: "🏳️", flagB: "🏳️", venue: "Estadio Azteca, Mexico City", group: "R32" },
      { id: 80, date: "Jul 01", time: "12:00", teamA: "1L", teamB: "3rd", flagA: "🏳️", flagB: "🏳️", venue: "Mercedes-Benz Stadium, Atlanta", group: "R32" },
      { id: 82, date: "Jul 01", time: "16:00", teamA: "1G", teamB: "3rd", flagA: "🏳️", flagB: "🏳️", venue: "Lumen Field, Seattle", group: "R32" },
      { id: 81, date: "Jul 01", time: "20:00", teamA: "1D", teamB: "3rd", flagA: "🏳️", flagB: "🏳️", venue: "Levi's Stadium, Santa Clara", group: "R32" },
      { id: 84, date: "Jul 02", time: "15:00", teamA: "1H", teamB: "2J", flagA: "🏳️", flagB: "🏳️", venue: "SoFi Stadium, Los Angeles", group: "R32" },
      { id: 83, date: "Jul 02", time: "19:00", teamA: "2K", teamB: "2L", flagA: "🏳️", flagB: "🏳️", venue: "BMO Field, Toronto", group: "R32" },
      { id: 85, date: "Jul 02", time: "23:00", teamA: "1B", teamB: "3rd", flagA: "🏳️", flagB: "🏳️", venue: "BC Place, Vancouver", group: "R32" },
      { id: 88, date: "Jul 03", time: "14:00", teamA: "2D", teamB: "2G", flagA: "🏳️", flagB: "🏳️", venue: "AT&T Stadium, Arlington", group: "R32" },
      { id: 86, date: "Jul 03", time: "18:00", teamA: "1J", teamB: "2H", flagA: "🏳️", flagB: "🏳️", venue: "Hard Rock Stadium, Miami", group: "R32" },
      { id: 87, date: "Jul 03", time: "21:30", teamA: "1K", teamB: "3rd", flagA: "🏳️", flagB: "🏳️", venue: "Arrowhead Stadium, Kansas City", group: "R32" },
    ],
  },
  {
    round: "Round of 16",
    games: [
      { id: 90, date: "Jul 04", time: "13:00", teamA: "W73", teamB: "W75", flagA: "🏳️", flagB: "🏳️", venue: "NRG Stadium, Houston", group: "R16" },
      { id: 89, date: "Jul 04", time: "17:00", teamA: "W74", teamB: "W77", flagA: "🏳️", flagB: "🏳️", venue: "Lincoln Financial Field, Philadelphia", group: "R16" },
      { id: 91, date: "Jul 05", time: "16:00", teamA: "W76", teamB: "W78", flagA: "🏳️", flagB: "🏳️", venue: "MetLife Stadium, New Jersey", group: "R16" },
      { id: 92, date: "Jul 05", time: "20:00", teamA: "W79", teamB: "W80", flagA: "🏳️", flagB: "🏳️", venue: "Estadio Azteca, Mexico City", group: "R16" },
      { id: 93, date: "Jul 06", time: "15:00", teamA: "W83", teamB: "W84", flagA: "🏳️", flagB: "🏳️", venue: "AT&T Stadium, Arlington", group: "R16" },
      { id: 94, date: "Jul 06", time: "20:00", teamA: "W81", teamB: "W82", flagA: "🏳️", flagB: "🏳️", venue: "Lumen Field, Seattle", group: "R16" },
      { id: 95, date: "Jul 07", time: "12:00", teamA: "W86", teamB: "W88", flagA: "🏳️", flagB: "🏳️", venue: "Mercedes-Benz Stadium, Atlanta", group: "R16" },
      { id: 96, date: "Jul 07", time: "16:00", teamA: "W85", teamB: "W87", flagA: "🏳️", flagB: "🏳️", venue: "BC Place, Vancouver", group: "R16" },
    ],
  },
  {
    round: "Quarter-Finals",
    games: [
      { id: 97, date: "Jul 09", time: "16:00", teamA: "W89", teamB: "W90", flagA: "🏳️", flagB: "🏳️", venue: "Gillette Stadium, Foxborough", group: "QF" },
      { id: 98, date: "Jul 10", time: "15:00", teamA: "W93", teamB: "W94", flagA: "🏳️", flagB: "🏳️", venue: "SoFi Stadium, Los Angeles", group: "QF" },
      { id: 99, date: "Jul 11", time: "17:00", teamA: "W91", teamB: "W92", flagA: "🏳️", flagB: "🏳️", venue: "Hard Rock Stadium, Miami", group: "QF" },
      { id: 100, date: "Jul 11", time: "21:00", teamA: "W95", teamB: "W96", flagA: "🏳️", flagB: "🏳️", venue: "Arrowhead Stadium, Kansas City", group: "QF" },
    ],
  },
  {
    round: "Semi-Finals",
    games: [
      { id: 101, date: "Jul 14", time: "15:00", teamA: "W97", teamB: "W98", flagA: "🏳️", flagB: "🏳️", venue: "AT&T Stadium, Arlington", group: "SF" },
      { id: 102, date: "Jul 15", time: "15:00", teamA: "W99", teamB: "W100", flagA: "🏳️", flagB: "🏳️", venue: "Mercedes-Benz Stadium, Atlanta", group: "SF" },
    ],
  },
  {
    round: "Third Place",
    games: [
      { id: 103, date: "Jul 18", time: "17:00", teamA: "L101", teamB: "L102", flagA: "🏳️", flagB: "🏳️", venue: "Hard Rock Stadium, Miami", group: "3rd" },
    ],
  },
  {
    round: "Final",
    games: [
      { id: 104, date: "Jul 19", time: "15:00", teamA: "W101", teamB: "W102", flagA: "🏳️", flagB: "🏳️", venue: "MetLife Stadium, New Jersey", group: "Final" },
    ],
  },
]

// Flat list for preview
export const upcomingGames = tournamentSchedule.flatMap((r) => r.games)

export const CATEGORIES = [
  "Sports Bar",
  "Pub",
  "Mexican",
  "American Grill",
  "Brewery",
  "Cocktail Bar",
  "Rooftop",
  "Family Restaurant",
  "Cafe",
  "Wing Joint",
  "Pizza Place",
  "Irish Bar",
  "Other",
]

// Emoji for each category (used in filter chips and map markers)
export const CATEGORY_EMOJI = {
  "Sports Bar": "\u{1F3C8}",
  "Pub": "\u{1F37A}",
  "Mexican": "\u{1F32E}",
  "American Grill": "\u{1F354}",
  "Brewery": "\u{1F37B}",
  "Cocktail Bar": "\u{1F378}",
  "Rooftop": "\u{1F307}",
  "Family Restaurant": "\u{1F37D}\uFE0F",
  "Cafe": "\u{2615}",
  "Wing Joint": "\u{1F357}",
  "Pizza Place": "\u{1F355}",
  "Irish Bar": "\u{2618}\uFE0F",
  "Other": "\u{1F37D}\uFE0F",
}

// Timezone offsets from ET (base times are in ET)
export const TIMEZONES = [
  { label: "ET", offset: 0, full: "Eastern Time" },
  { label: "CT", offset: -1, full: "Central Time" },
  { label: "MT", offset: -2, full: "Mountain Time" },
  { label: "PT", offset: -3, full: "Pacific Time" },
  { label: "GMT", offset: 5, full: "Greenwich Mean Time" },
  { label: "CET", offset: 6, full: "Central European Time" },
]
